"""
Revien Distill-Out — write what Revien holds back into the vault as markdown.

"Your AI's memory is files you can open." The distiller renders a read-only
markdown VIEW of the graph into a dedicated folder inside the user's Obsidian
vault: one note per entity, every claim carrying its provenance (source,
content date, confidence, curated-or-machine), related entities as
[[wikilinks]] — so Revien's memory threads into the vault's own graph pane.

HARD RULES (the reason this is safe to point at a real vault):
  * WRITES ONLY inside `<vault>/<folder>/` (default "Revien"). Never touches
    a user note, anywhere, ever.
  * Every generated file carries `revien: derived` frontmatter. The distiller
    will only overwrite or prune files that carry the marker — a user note
    that wanders into the folder is left alone.
  * The Obsidian ingest adapter SKIPS any note with the marker, so distilled
    memory never feeds back into the graph (no echo loop).
  * Deterministic: same graph state -> byte-identical files (stable ordering,
    no timestamps in content). Files are only rewritten when content actually
    changed, so vault sync tools don't see phantom churn.
  * The graph is never mutated — distill-out is a pure read.

Vault-echo guard: an entity whose only attached claims came FROM the vault is
skipped — the user already wrote that note; echoing it back is noise. An
entity earns a distilled note by holding at least `min_claims` machine-side
claims (things the vault does NOT already know).
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from revien.graph.schema import Node, NodeType
from revien.graph.store import GraphStore

MARKER_KEY = "revien"
MARKER_VALUE = "derived"
DEFAULT_FOLDER = "Revien"

# Claim-bearing node types rendered into a distilled note, in section order.
_SECTIONS: List[Tuple[NodeType, str]] = [
    (NodeType.DECISION, "Decisions"),
    (NodeType.FACT, "Facts"),
    (NodeType.PREFERENCE, "Preferences"),
    (NodeType.EVENT, "Events"),
]


def _safe_filename(label: str) -> str:
    """Entity label -> filesystem/Obsidian-safe filename stem."""
    cleaned = re.sub(r"[^\w\- ]+", "", label).strip()
    cleaned = re.sub(r"\s+", " ", cleaned)
    return cleaned or "entity"


def _linkable(label: str) -> bool:
    """A label that can live inside [[...]] without breaking markdown. Junk
    graph entities (extractor noise spanning newlines, bracket-bearing labels)
    must degrade to 'not linked', never to broken output."""
    return bool(label.strip()) and not re.search(r"[\n\r\[\]|#]", label)


def _provenance(node: Node) -> str:
    """One human-readable parenthetical per claim: where it came from, when
    it was said, how much we trust it."""
    md = node.metadata or {}
    if md.get("curated"):
        note = md.get("note")
        source = f"vault: {note}" if note else "vault"
    else:
        adapter = md.get("adapter")
        source = adapter if adapter else "conversation"
    parts = [source]
    if node.recorded_at is not None:
        parts.append(node.recorded_at.strftime("%Y-%m-%d"))
    parts.append(f"confidence {node.confidence:.2f}")
    return ", ".join(parts)


class VaultDistiller:
    """Render the graph's entity views into `<vault>/<folder>/` markdown."""

    def __init__(
        self,
        store: GraphStore,
        vault_dir: str,
        folder: str = DEFAULT_FOLDER,
        min_claims: int = 1,
    ):
        self.store = store
        self.vault_dir = Path(vault_dir)
        self.out_dir = self.vault_dir / folder
        self.min_claims = max(1, int(min_claims))

    # ── Gather ─────────────────────────────────────────────

    def _claims_for(self, entity: Node) -> Tuple[List[Node], List[Node]]:
        """(claims, related_entities) attached to an entity — live nodes only."""
        claims: List[Node] = []
        related: List[Node] = []
        for nid in self.store.get_neighbors(entity.node_id):
            node = self.store.get_node(nid)
            if node is None or node.invalidated_at is not None:
                continue
            if node.node_type == NodeType.ENTITY:
                related.append(node)
            elif any(node.node_type == t for t, _ in _SECTIONS):
                claims.append(node)
        return claims, related

    # ── Render ─────────────────────────────────────────────

    def _render(self, entity: Node, claims: List[Node], related: List[Node]) -> str:
        lines = [
            "---",
            f"{MARKER_KEY}: {MARKER_VALUE}",
            f"entity: {entity.label}",
            "---",
            "",
            f"# {entity.label} — Revien memory",
            "",
            "> Generated by Revien from its memory graph. Read-only view —",
            "> edits here are not ingested and are overwritten on the next distill.",
        ]
        for node_type, title in _SECTIONS:
            section = sorted(
                (c for c in claims if c.node_type == node_type),
                key=lambda c: (
                    c.recorded_at.isoformat() if c.recorded_at else "",
                    c.label.lower(),
                    c.node_id,
                ),
            )
            if not section:
                continue
            lines += ["", f"## {title}", ""]
            for claim in section:
                text = " ".join((claim.content or claim.label).split())
                lines.append(f"- {text} *({_provenance(claim)})*")
        if related:
            names = sorted(
                {
                    r.label for r in related
                    if r.label != entity.label and _linkable(r.label)
                },
                key=str.lower,
            )
            if names:
                lines += ["", "## Related", ""]
                lines.append(" · ".join(f"[[{n}]]" for n in names))
        return "\n".join(lines) + "\n"

    def _render_index(self, entries: List[Tuple[str, int]]) -> str:
        lines = [
            "---",
            f"{MARKER_KEY}: {MARKER_VALUE}",
            "entity: __index__",
            "---",
            "",
            "# Revien memory index",
            "",
            "> One note per entity Revien holds machine-side memory about.",
            "",
        ]
        for stem, n_claims in sorted(entries, key=lambda e: e[0].lower()):
            lines.append(f"- [[{stem}]] ({n_claims} claim{'s' if n_claims != 1 else ''})")
        return "\n".join(lines) + "\n"

    # ── Write / prune (marker-gated) ───────────────────────

    @staticmethod
    def _has_marker(path: Path) -> bool:
        try:
            head = path.read_text(encoding="utf-8", errors="replace")[:400]
        except OSError:
            return False
        m = re.match(r"\A---\s*\n(.*?)\n---", head, re.DOTALL)
        return bool(m) and bool(
            re.search(rf"^{MARKER_KEY}:\s*{MARKER_VALUE}\s*$", m.group(1), re.MULTILINE)
        )

    def _write_if_changed(self, path: Path, content: str) -> bool:
        if path.exists():
            if not self._has_marker(path):
                # A user file where we wanted to write: theirs. Skip loudly
                # in the summary rather than overwrite silently.
                return False
            try:
                if path.read_text(encoding="utf-8") == content:
                    return False  # unchanged — no phantom churn
            except OSError:
                pass
        path.write_text(content, encoding="utf-8", newline="\n")
        return True

    # ── Entry point ────────────────────────────────────────

    def distill(self) -> Dict:
        """Regenerate the distilled view. Returns a summary dict."""
        if not self.vault_dir.is_dir():
            return {"status": "error", "error": f"vault not found: {self.vault_dir}"}
        self.out_dir.mkdir(parents=True, exist_ok=True)

        entities = self.store.list_nodes(node_type=NodeType.ENTITY, limit=999999)
        generated: Dict[str, str] = {}  # filename stem -> content
        skipped_vault_echo = 0
        index_entries: List[Tuple[str, int]] = []

        for entity in sorted(entities, key=lambda e: (e.label.lower(), e.node_id)):
            if entity.invalidated_at is not None or not entity.label.strip():
                continue
            claims, related = self._claims_for(entity)
            machine_claims = [
                c for c in claims if not (c.metadata or {}).get("curated")
            ]
            if len(machine_claims) < self.min_claims:
                if claims:
                    skipped_vault_echo += 1
                continue

            stem = _safe_filename(entity.label)
            if stem in generated:  # label collision after sanitizing
                stem = f"{stem} ({entity.node_id[:8]})"
            generated[stem] = self._render(entity, claims, related)
            index_entries.append((stem, len(claims)))

        if index_entries:
            generated["_Revien Index"] = self._render_index(index_entries)

        written = sum(
            1 for stem, content in generated.items()
            if self._write_if_changed(self.out_dir / f"{stem}.md", content)
        )

        # Prune: OUR stale files only (marker-gated). User files are inviolate.
        pruned = 0
        keep = {f"{stem}.md" for stem in generated}
        for path in self.out_dir.glob("*.md"):
            if path.name not in keep and self._has_marker(path):
                path.unlink()
                pruned += 1

        return {
            "status": "ok",
            "notes": len(index_entries),
            "written": written,
            "unchanged": len(generated) - written,
            "pruned": pruned,
            "skipped_vault_echo": skipped_vault_echo,
            "out_dir": str(self.out_dir),
        }
